// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyrW5tcI8yOBCyogSJK8CRDlwUHfD0qwA',
    appId: '1:52606566891:web:dd34270997137e326d59ae',
    messagingSenderId: '52606566891',
    projectId: 'lapoapp-44966',
    authDomain: 'lapoapp-44966.firebaseapp.com',
    storageBucket: 'lapoapp-44966.appspot.com',
    measurementId: 'G-9Q9NV6S0CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs-y83GWnEDHWUEd1Ko2HZTGaKy8nWYPc',
    appId: '1:52606566891:android:02d103cfd3addfb96d59ae',
    messagingSenderId: '52606566891',
    projectId: 'lapoapp-44966',
    storageBucket: 'lapoapp-44966.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGApQemQtaXYg8YFAOmbShEJe9Jm4KUn0',
    appId: '1:52606566891:ios:081bf15f2c7b4a2e6d59ae',
    messagingSenderId: '52606566891',
    projectId: 'lapoapp-44966',
    storageBucket: 'lapoapp-44966.appspot.com',
    iosBundleId: 'com.example.lapoUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGApQemQtaXYg8YFAOmbShEJe9Jm4KUn0',
    appId: '1:52606566891:ios:0309fbe54ab336bc6d59ae',
    messagingSenderId: '52606566891',
    projectId: 'lapoapp-44966',
    storageBucket: 'lapoapp-44966.appspot.com',
    iosBundleId: 'com.example.lapoUser.RunnerTests',
  );
}
